\" manpage for kbdlight
.\" Contact juan.cuzmar.s@gmail.com to correct errors or typos
.TH kbdlight 1 "21 September 2019" "version 1.1" "kbdlight manpage"
.SH NAME
kbdlight - change keyboard backlight brightness
.SH SYNOPSIS
.B kbdlight
.RI "[" OPTION "]"
.SH DESCRIPTION
.B kbdlight
allows the user to change the brightness of a backlit keyboard using /sys/class/leds.
.br
The program works in userspace by changing the value in the brightness file provided by the kernel in /sys/class/leds/.
.br
For this to work, the kernel must support this type of control, the user must have appropiate permissions (in most distros, the video group is sufficient) and the hardware must expose the backlight to the kernel.
.SH OPTIONS
.TP
.B -i
Increase brightness by one
.TP
.B -d
Decrease brightness by one
.TP
.B -c
Get current brightness value
.TP
.B -h
Prints usage.
.SH EXIT STATUS
.TP
0
Success.
.TP
1
Error.
.SH AUTHOR
Juan Cuzmar (juan.cuzmar.s@gmail.com)
.SH "REPORTING BUGS"
Open an issue in <https://github.com/glats/kbdlight/issues>
.br
To correct errors or typos send an email <juan.cuzmar.s@gmail.com>
.SH COPYRIGHT
This is free software, see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE